language: node_js
sudo: 'false'
before_script:
    - npm install -g polymer-cli
    - git checkout package-lock.json
    - >-
      npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
      Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: K4VgzWGTtrmpfr0mweonk3jfSqSQ9QW+FOtPNN7LjNqIdOn2aw40saQEYWQRqwjuGvaI1rvkGSTauvsNLaXZuKfxc0apC+nysPegz4m7B38nWf5XBvNujRtrj5NDIV13R6qKkNE6Mfm9SOalNDfk5ZQSJLIvj87Kb/WZGwq4o9XyY3No5NmrMztpdwQk8rStgNmy7//aly1XVxaPG/Pb1uSPWIG5+sWh6Lcg+R1J6i+Gk/ItQFGYonNNoU/ahvDU95wXzeN3cCb+ky1mBqB0KFZgxEElHjddxaLuj8FFfC4c2yilaAiFvCDOkfgy0taPPacdiySTq8Dr9lVk+kaGUt12GMBkgbBWCUBmtrQpDFa8JOQTo7IzbdQiOd++LGNOLmnWJ/g7ETETnqFtKM3fiNcvQy9ek9GMVmRrr6ZrCtVafKjBdOfGzGh3yl1GY0ZTFi2ro1qwv1qU43PKlhvxc/FAvWKwJPqJoB2/4OXdLza/N7sHA8AqvjHUqKAaZnpTyxUBixgboiYqwu8DimP0wyJim3ZGUodppae0cFDQDb3mRWYhyUdP7Ul5KuMid2QLDVCbEHroNzK7PNYMemU8GJAKPA8f9hHhp5/5VlkMLUMU/shkDO8uumsC8zM8gm5w0wOHX2U48CT0CzB/0/yA0aPUZ3Mg5sNb8o5NX8+2dMg=
    - secure: sgXf0tTluAfwr/oFBlR300+WxGY2ZT6fBUV2Cp0XvsheqVlyeGK5vsi8JjiVcpD/W2/yr1gYnJ/HC/HsCJan/RyYVyDPjn5RZE78elDOp6vYikdp4gXv1Wa4j/H/cm0zkRZ7dBGE0e9EtO6NWzBQw9wnaISvMLfBaAoz2m2X9fgA/WwMaQHlp8kklglkJUhvrzyo2LLQvM8h1RxoiRlarVjQx7/neiX1GUBurghId+s62B+j50XtkZdWJbFzDFeXDZKIHQ7a/vfZK7TWG43eJaAtBfyKyGbo72RvlzwQQ+3k0E4h/cZ4Zp9d6IYiwZeQmU/WncZw7anbZOobyR7abwpEM01YcmB6HJtSDxHUrfXbJvYgyWz6HyqlUj6ShD7PzSiMoJJX5qZX18ziPPr4/w50jRT1IJDnyOogPVTjr1PYK+W9w6IBtsoorSsEmFPygOgpuNSO3/dr7Olpgx5B3qEEbnbj2w5J66VYuHrDYV6G4IQlAr4UPIGJwgbB2A7+4CrxbQ+L/GjW+HmTplUq6pm8q8CDa+Qt7EYqXOXe9Apc7oDUe1pO/ShP5RwU2mFiRk9HhhkcGRewSO4eyNpVgpjvuMuQgRkpmBkHcw6nwtAfgy/tdWLvCGqORqJb/6bM+FWRPBGqeDUSZHYXMzaRh5kamiZ/QWqqRKB+h4tbggc=
node_js: 'node'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test --module-resolution=node --npm
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node --npm -s ''default''; fi'
dist: trusty
cache:
  directories:
    - node_modules
